### ISSUE TITLE
what is this repository?

### ISSUE THREAD

**Issue by ktdreyer** [puiterwijk/mbbox#3]
I could not tell what this repository is when I look at the README file.

What is in scope and out of scope for this project?

**Comment by ktdreyer** [comment]
I see some clues at https://blog.centos.org/2019/06/centos-8-status-17-june-2019/

**Comment by puiterwijk** [comment]
@ktdreyer Hey, thanks for reporting this.
This project definitely needs some intro text, and I'll try to look at that coming week!
This was intended to allow people to quickly set up a koji/MBS setup in openshift, in a way that is still production-grade.
So it's intended to be a quick way to set it up, but also allow the same setup to be used in larger production setups.

**Comment by ktdreyer** [comment]
Great, thanks Patrick
